// AUTO-GENERATED PARSED FROM JAVA CONTROLLERS
const ZAP_API_DATA = {
  "services": [
    {
      "id": "all",
      "name": "All Services (Auto-Synced)",
      "icon": "\u26a1"
    },
    {
      "id": "gateway",
      "name": "API Gateway",
      "icon": "\ud83c\udf10",
      "port": 8080
    },
    {
      "id": "identity",
      "name": "Identity Service",
      "icon": "\ud83d\udd10",
      "port": 8081
    },
    {
      "id": "commerce",
      "name": "Commerce Service",
      "icon": "\ud83d\uded2",
      "port": 8082
    },
    {
      "id": "payment",
      "name": "Payment Service",
      "icon": "\ud83d\udcb3",
      "port": 8083
    },
    {
      "id": "notification",
      "name": "Notification Service",
      "icon": "\ud83d\udd14",
      "port": 8084
    }
  ],
  "securityHeaders": [
    {
      "name": "Authorization",
      "description": "JWT Access Token formatted as Bearer <token>",
      "required": true,
      "example": "Bearer eyJhbGciOiJIUzUx..."
    },
    {
      "name": "x-auth-signature",
      "description": "RSA 2048-bit digital signature generated by hardware chip (Secure Enclave / TEE)",
      "required": true,
      "example": "Base64SignatureString=="
    },
    {
      "name": "x-auth-timestamp",
      "description": "Unix epoch timestamp in milliseconds (max 5 min drift)",
      "required": true,
      "example": "1723205160000"
    },
    {
      "name": "x-auth-nonce",
      "description": "Cryptographic random nonce to prevent replay attacks",
      "required": true,
      "example": "nonce_a98f12"
    },
    {
      "name": "x-auth-checksum",
      "description": "SHA-256 hash digest of the raw HTTP request body",
      "required": true,
      "example": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    }
  ],
  "endpoints": [],
  "commitActivity": [
    {
      "name": "identity-service",
      "total": 12,
      "color": "#10B981",
      "recent": []
    },
    {
      "name": "commerce-service",
      "total": 12,
      "color": "#3B82F6",
      "recent": []
    },
    {
      "name": "payment-service",
      "total": 12,
      "color": "#8B5CF6",
      "recent": []
    },
    {
      "name": "notification-service",
      "total": 12,
      "color": "#F59E0B",
      "recent": []
    },
    {
      "name": "api-gateway",
      "total": 12,
      "color": "#EC4899",
      "recent": []
    }
  ]
};
