// AUTO-GENERATED PARSED DIRECTLY FROM JAVA CONTROLLER SOURCE CODE IN backend/
const ZAP_API_DATA = {
  services: [
  {
    "id": "all",
    "name": "All Services (0 Endpoints)",
    "icon": "\u26a1"
  },
  {
    "id": "gateway",
    "name": "API Gateway (0)",
    "icon": "\ud83c\udf10",
    "port": 8080
  },
  {
    "id": "identity",
    "name": "Identity Service (0)",
    "icon": "\ud83d\udd10",
    "port": 8081
  },
  {
    "id": "commerce",
    "name": "Commerce Service (0)",
    "icon": "\ud83d\uded2",
    "port": 8082
  },
  {
    "id": "payment",
    "name": "Payment Service (0)",
    "icon": "\ud83d\udcb3",
    "port": 8083
  },
  {
    "id": "notification",
    "name": "Notification Service (0)",
    "icon": "\ud83d\udd14",
    "port": 8084
  }
],
  securityHeaders: [
  {
    "name": "Authorization",
    "description": "JWT Access Token formatted as Bearer <token>",
    "required": true,
    "example": "Bearer eyJhbGciOiJIUzUx..."
  },
  {
    "name": "x-auth-signature",
    "description": "RSA 2048-bit digital signature generated by hardware chip (Secure Enclave / TEE)",
    "required": true,
    "example": "Base64SignatureString=="
  },
  {
    "name": "x-auth-timestamp",
    "description": "Unix epoch timestamp in milliseconds (max 5 min drift)",
    "required": true,
    "example": "1723205160000"
  },
  {
    "name": "x-auth-nonce",
    "description": "Cryptographic random nonce to prevent replay attacks",
    "required": true,
    "example": "nonce_a98f12"
  },
  {
    "name": "x-auth-checksum",
    "description": "SHA-256 hash digest of the raw HTTP request body",
    "required": true,
    "example": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
  },
  {
    "name": "x-internal-call",
    "description": "Internal microservice header (bypasses RSA signature check)",
    "required": false,
    "example": "true"
  }
],
  endpoints: []
};
