#!/usr/bin/env python3
"""
ZAP Backend Java Controller Scanner & Real Git Commit Activity Generator
Scans all Spring Boot @RestController Java files and Real Git commit logs in backend/
Auto-generates docs/system-design/js/api-data.js
"""

import os
import re
import json
import subprocess

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SYSTEM_DESIGN_DIR = os.path.dirname(SCRIPT_DIR)
DOCS_DIR = os.path.dirname(SYSTEM_DESIGN_DIR)
WORKSPACE_ROOT = os.path.dirname(DOCS_DIR)

BACKEND_DIR = os.path.join(WORKSPACE_ROOT, "backend")
if not os.path.exists(BACKEND_DIR):
    BACKEND_DIR = os.path.join(DOCS_DIR, "backend")
if not os.path.exists(BACKEND_DIR):
    BACKEND_DIR = "/Volumes/Transcend/projects/zap-system/backend"

OUTPUT_FILE = os.path.join(SYSTEM_DESIGN_DIR, "js", "api-data.js")

SERVICES = [
    { "id": "all", "name": "All Services (Auto-Synced)", "icon": "⚡" },
    { "id": "gateway", "name": "API Gateway", "icon": "🌐", "port": 8080 },
    { "id": "identity", "name": "Identity Service", "icon": "🔐", "port": 8081 },
    { "id": "commerce", "name": "Commerce Service", "icon": "🛒", "port": 8082 },
    { "id": "payment", "name": "Payment Service", "icon": "💳", "port": 8083 },
    { "id": "notification", "name": "Notification Service", "icon": "🔔", "port": 8084 }
]

SECURITY_HEADERS = [
    { "name": "Authorization", "description": "JWT Access Token formatted as Bearer <token>", "required": True, "example": "Bearer eyJhbGciOiJIUzUx..." },
    { "name": "x-auth-signature", "description": "RSA 2048-bit digital signature generated by hardware chip (Secure Enclave / TEE)", "required": True, "example": "Base64SignatureString==" },
    { "name": "x-auth-timestamp", "description": "Unix epoch timestamp in milliseconds (max 5 min drift)", "required": True, "example": "1723205160000" },
    { "name": "x-auth-nonce", "description": "Cryptographic random nonce to prevent replay attacks", "required": True, "example": "nonce_a98f12" },
    { "name": "x-auth-checksum", "description": "SHA-256 hash digest of the raw HTTP request body", "required": True, "example": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" },
    { "name": "x-internal-call", "description": "Internal microservice header (bypasses RSA signature check)", "required": False, "example": "true" }
]

def get_service_id(filepath):
    if "identity-service" in filepath:
        return "identity", "Identity Service"
    elif "commerce-service" in filepath:
        return "commerce", "Commerce Service"
    elif "payment-service" in filepath or "payment_service" in filepath:
        return "payment", "Payment Service"
    elif "notification-service" in filepath or "notification" in filepath:
        return "notification", "Notification Service"
    elif "api-gateway" in filepath:
        return "gateway", "API Gateway"
    return "commerce", "Commerce Service"

def scan_git_commits():
    commit_activity = []
    repo_dirs = [
        ("identity-service", "#10B981"),
        ("commerce-service", "#3B82F6"),
        ("payment-service", "#8B5CF6"),
        ("notification-service", "#F59E0B"),
        ("api-gateway", "#EC4899")
    ]

    for repo_name, color in repo_dirs:
        target_dir = os.path.join(BACKEND_DIR, repo_name)
        if not os.path.exists(target_dir):
            target_dir = WORKSPACE_ROOT

        try:
            cmd = ["git", "log", "-n", "20", "--pretty=format:%h|%an|%s|%cd", "--date=short"]
            res = subprocess.run(cmd, cwd=target_dir, capture_output=True, text=True, check=True)
            lines = res.stdout.strip().split("\n")
            recent_commits = []
            for line in lines:
                if not line: continue
                parts = line.split("|")
                if len(parts) >= 3:
                    recent_commits.append({
                        "hash": parts[0],
                        "author": parts[1],
                        "msg": parts[2],
                        "date": parts[3] if len(parts) > 3 else ""
                    })
            
            cnt_cmd = ["git", "rev-list", "--count", "HEAD"]
            cnt_res = subprocess.run(cnt_cmd, cwd=target_dir, capture_output=True, text=True)
            total_cnt = int(cnt_res.stdout.strip()) if cnt_res.returncode == 0 else len(recent_commits)

            commit_activity.append({
                "name": repo_name,
                "color": color,
                "total": total_cnt,
                "recent": recent_commits
            })
        except Exception as e:
            commit_activity.append({
                "name": repo_name,
                "color": color,
                "total": 0,
                "recent": []
            })
    return commit_activity

def scan_java_controllers():
    endpoints = []
    ep_counter = 0

    if not os.path.exists(BACKEND_DIR):
        print(f"⚠️ Directory {BACKEND_DIR} not found.")
        return endpoints

    for root, _, files in os.walk(BACKEND_DIR):
        for file in files:
            if file.endswith(".java") and ("Controller" in file or "Endpoint" in file):
                filepath = os.path.join(root, file)
                service_id, service_name = get_service_id(filepath)
                class_basename = file.replace(".java", "")

                try:
                    with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
                        content = f.read()

                    base_path = ""
                    class_req_match = re.search(r'@RequestMapping\s*\(\s*["\']([^"\']+)["\']', content)
                    if not class_req_match:
                        class_req_match = re.search(r'@RequestMapping\s*\(\s*value\s*=\s*["\']([^"\']+)["\']', content)
                    if class_req_match:
                        base_path = class_req_match.group(1).rstrip("/")

                    method_pattern = r'@(GetMapping|PostMapping|PutMapping|DeleteMapping|RequestMapping)\s*(\([^)]*\))?\s*(?:public|private|protected)?\s+[\w<>,?\s]+\s+(\w+)\s*\('
                    
                    for match in re.finditer(method_pattern, content):
                        ann_type = match.group(1)
                        ann_args = match.group(2) or ""
                        func_name = match.group(3)

                        http_method = "GET"
                        if ann_type == "PostMapping": http_method = "POST"
                        elif ann_type == "PutMapping": http_method = "PUT"
                        elif ann_type == "DeleteMapping": http_method = "DELETE"
                        elif ann_type == "RequestMapping":
                            m_match = re.search(r'method\s*=\s*RequestMethod\.(\w+)', ann_args)
                            if m_match: http_method = m_match.group(1).upper()

                        sub_path = ""
                        path_match = re.search(r'["\']([^"\']+)["\']', ann_args)
                        if path_match:
                            sub_path = path_match.group(1)
                            if not sub_path.startswith("/"): sub_path = "/" + sub_path

                        full_path = base_path + sub_path
                        if not full_path.startswith("/"): full_path = "/" + full_path

                        is_public = "public" in full_path.lower() or "auth" in full_path.lower() or "login" in full_path.lower()
                        is_internal = "internal" in full_path.lower() or "Internal" in class_basename
                        is_crm = "crm" in full_path.lower() or "Crm" in class_basename

                        ep_id = f"{service_id}-{func_name.lower()}-{ep_counter}"
                        ep_counter += 1

                        summary_text = f"{func_name.capitalize()} ({class_basename})"
                        desc_text = f"Java Controller: {class_basename}.java | Method: {func_name}()"

                        endpoints.append({
                            "id": ep_id,
                            "service": service_id,
                            "serviceName": service_name,
                            "method": http_method,
                            "path": full_path,
                            "summary": summary_text,
                            "description": desc_text,
                            "isPublic": is_public,
                            "isInternal": is_internal,
                            "isCrm": is_crm,
                            "requiresSignature": not is_public and not is_internal,
                            "requestBody": None if http_method == "GET" else { "example": "Payload JSON" },
                            "responses": {
                                "200": {
                                    "code": 1000,
                                    "message": "Operation Successful",
                                    "data": {}
                                }
                            }
                        })

                except Exception as e:
                    print(f"Error reading {filepath}: {e}")

    return endpoints

def generate_js_data():
    endpoints = scan_java_controllers()
    commit_activity = scan_git_commits()

    if len(endpoints) == 0:
        print("⚠️ 0 endpoints scanned. Keeping existing api-data.js safely to prevent data loss!")
        return

    svc_counts = {}
    for ep in endpoints:
        s = ep["service"]
        svc_counts[s] = svc_counts.get(s, 0) + 1

    services = []
    for s in SERVICES:
        if s["id"] == "all":
            services.append({ **s, "name": f"All Services ({len(endpoints)} Endpoints)" })
        else:
            cnt = svc_counts.get(s["id"], 0)
            services.append({ **s, "name": f"{s['name'].split(' (')[0]} ({cnt})" })

    js_content = f"""// AUTO-GENERATED PARSED DIRECTLY FROM JAVA CONTROLLER SOURCE CODE AND REAL GIT LOGS IN backend/
const ZAP_API_DATA = {{
  services: {json.dumps(services, indent=2)},
  securityHeaders: {json.dumps(SECURITY_HEADERS, indent=2)},
  commitActivity: {json.dumps(commit_activity, indent=2)},
  endpoints: {json.dumps(endpoints, indent=2)}
}};
"""

    os.makedirs(os.path.dirname(OUTPUT_FILE), exist_ok=True)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"✅ Successfully scanned {len(endpoints)} API endpoints and real Git commit logs!")
    print(f"📄 Output saved to: {OUTPUT_FILE}")

if __name__ == "__main__":
    generate_js_data()
